#include "testcontainers/modules/Mosquitto.hpp"

#include <string>
#include <utility>

#include "testcontainers/Error.hpp"
#include "testcontainers/WaitFor.hpp"

namespace testcontainers::modules {

MosquittoImage::MosquittoImage()
    : image_(GenericImage::from_reference(std::string(kDefaultImage))) {
    // Baked once, never touched by rendering. The broker prints "mosquitto
    // version X.Y.Z running" AFTER its listening sockets are open (verified
    // in the 2.0.x sources: the line follows listeners__start()), so there is
    // no log/listener race to force a TCP or exec probe over — and an exec
    // probe would break under user-replaced auth configs. Default log_dest is
    // stderr; the either-stream wait survives a replacement config's
    // `log_dest stdout`.
    image_.with_exposed_port(tcp(kPort)).with_wait(wait_for::log("running"));
}

MosquittoImage& MosquittoImage::with_image(const std::string& reference) {
    image_.with_image(reference);
    return *this;
}

MosquittoImage& MosquittoImage::with_config_option(std::string key, std::string value) {
    config_options_.emplace_back(std::move(key), std::move(value));
    return *this;
}

MosquittoImage& MosquittoImage::with_config(std::filesystem::path host_conf) {
    user_config_ = CopyToContainer::host_file(std::move(host_conf), std::string(kConfigPath));
    return *this;
}

MosquittoImage& MosquittoImage::with_config_content(std::string conf) {
    user_config_ = CopyToContainer::content(std::move(conf), std::string(kConfigPath));
    return *this;
}

MosquittoImage& MosquittoImage::with_env(std::string key, std::string value) {
    image_.with_env(std::move(key), std::move(value));
    return *this;
}

MosquittoImage& MosquittoImage::with_label(std::string key, std::string value) {
    image_.with_label(std::move(key), std::move(value));
    return *this;
}

MosquittoImage& MosquittoImage::with_network(std::string network) {
    image_.with_network(std::move(network));
    return *this;
}

MosquittoImage& MosquittoImage::with_network(const Network& network) {
    image_.with_network(network);
    return *this;
}

MosquittoImage& MosquittoImage::with_network_alias(std::string alias) {
    image_.with_network_alias(std::move(alias));
    return *this;
}

MosquittoImage& MosquittoImage::with_reuse(bool reuse) {
    image_.with_reuse(reuse);
    return *this;
}

MosquittoImage& MosquittoImage::with_startup_timeout(std::chrono::milliseconds timeout) {
    image_.with_startup_timeout(timeout);
    return *this;
}

MosquittoImage& MosquittoImage::with_startup_attempts(int n) {
    image_.with_startup_attempts(n);
    return *this;
}

MosquittoImage& MosquittoImage::with_customizer(std::function<void(GenericImage&)> customize) {
    customizers_.push_back(std::move(customize));
    return *this;
}

GenericImage MosquittoImage::to_generic() const {
    // Fail fast, before any daemon contact: mosquitto's config is order-
    // sensitive and listener-scoped, so "merging" option lines into a
    // user-owned file has no well-defined meaning.
    if (user_config_.has_value() && !config_options_.empty()) {
        throw Error("with_config_option cannot be combined with a replacement config "
                    "(with_config / with_config_content) — mosquitto options are order- and "
                    "listener-scoped, so put the line in your config file instead");
    }

    // Render into a COPY: repeated to_generic()/start() calls must never
    // accumulate state in the config.
    GenericImage generic = image_;
    if (user_config_.has_value()) {
        generic.with_copy_to(*user_config_);
    } else {
        // The managed config: what the image's own no-auth quickstart file
        // ships, generated as a pure function of the options — no timestamps —
        // so identical configs stay reuse-hash-identical (byte sources
        // contribute content verbatim to the hash).
        std::string conf = "# Generated by testcontainers-cpp (MosquittoImage).\n"
                           "listener " +
                           std::to_string(kPort) +
                           "\n"
                           "allow_anonymous true\n";
        for (const auto& [key, value] : config_options_) {
            conf += key + " " + value + "\n";
        }
        generic.with_copy_to(CopyToContainer::content(std::move(conf), std::string(kConfigPath)));
    }

    // Customizers last: what the escape hatch sets wins over the module's
    // rendering, mirroring how with_create_body_patch wins over typed fields.
    for (const auto& customize : customizers_) {
        customize(generic);
    }
    return generic;
}

MosquittoContainer MosquittoImage::start() const {
    return MosquittoContainer(to_generic().start());
}

} // namespace testcontainers::modules
