#include <gtest/gtest.h>

#include <chrono>
#include <string>
#include <variant>
#include <vector>

#include "testcontainers/Error.hpp"
#include "testcontainers/GenericImage.hpp"
#include "testcontainers/WaitFor.hpp"
#include "testcontainers/modules/Mosquitto.hpp"

// Tests in this file (unit; no Docker daemon — the module's rendering rules
// via to_generic()):
//   MosquittoModuleConfig.DefaultRendersPinPortWaitAndManagedConfig - the default config renders the pinned image, exposes 1883/tcp, installs the "running" log wait, ships the managed listener+anonymous config bytes to the image's config path, and leaves cmd/env untouched.
//   MosquittoModuleConfig.ConfigOptionsAppendInCallOrder - with_config_option lines land after the managed block in call order, and config_options() reports them.
//   MosquittoModuleConfig.ReplacementConfigReplacesAndLastWins - with_config_content/with_config replace the managed config entirely (bytes or host file at the config path); repeat calls replace again, last one wins.
//   MosquittoModuleConfig.OptionsPlusReplacementThrowAtRender - combining with_config_option with a replacement config throws at render, in either call order.
//   MosquittoModuleConfig.CustomizerRunsLastAndWins - a customizer sees the module-rendered builder (config copy staged) and what it sets wins.
//   MosquittoModuleConfig.WithImageRewritesReference - with_image swaps name and tag (bare name defaults to "latest") while the rest of the config survives.
//   MosquittoModuleConfig.RenderingIsIdempotent - to_generic() renders into a copy: repeated renders are equal and the config never accumulates staged copies.
//   MosquittoModuleConfig.PassThroughsLandOnTheImage - the env/label/network/alias/reuse/timeout/attempts pass-throughs reach the rendered builder.

using namespace testcontainers;
using modules::MosquittoImage;

namespace {

constexpr const char* kManagedConfig = "# Generated by testcontainers-cpp (MosquittoImage).\n"
                                       "listener 1883\n"
                                       "allow_anonymous true\n";

} // namespace

TEST(MosquittoModuleConfig, DefaultRendersPinPortWaitAndManagedConfig) {
    const GenericImage generic = MosquittoImage().to_generic();

    EXPECT_EQ(generic.image(), "eclipse-mosquitto");
    EXPECT_EQ(generic.tag(), "2.0");
    ASSERT_EQ(generic.exposed_ports().size(), 1u);
    EXPECT_EQ(generic.exposed_ports()[0], tcp(1883));

    ASSERT_EQ(generic.waits().size(), 1u);
    const auto* log = std::get_if<wait_for::LogMessage>(&generic.waits()[0]);
    ASSERT_NE(log, nullptr);
    EXPECT_EQ(log->text, "running");
    EXPECT_EQ(log->source, wait_for::LogMessage::Source::Either);

    ASSERT_EQ(generic.copy_to_sources().size(), 1u);
    const CopyToContainer& conf = generic.copy_to_sources()[0];
    EXPECT_FALSE(conf.is_file());
    EXPECT_FALSE(conf.is_dir());
    EXPECT_EQ(conf.target(), "/mosquitto/config/mosquitto.conf");
    EXPECT_EQ(conf.bytes(), kManagedConfig);

    // The image's own command keeps applying; the module owns only the config file.
    EXPECT_TRUE(generic.cmd().empty());
    EXPECT_TRUE(generic.env().empty());
}

TEST(MosquittoModuleConfig, ConfigOptionsAppendInCallOrder) {
    MosquittoImage cfg;
    cfg.with_config_option("persistence", "true").with_config_option("max_keepalive", "120");

    const GenericImage generic = cfg.to_generic();
    ASSERT_EQ(generic.copy_to_sources().size(), 1u);
    EXPECT_EQ(generic.copy_to_sources()[0].bytes(),
              std::string(kManagedConfig) + "persistence true\nmax_keepalive 120\n");

    ASSERT_EQ(cfg.config_options().size(), 2u);
    EXPECT_EQ(cfg.config_options()[0].first, "persistence");
    EXPECT_EQ(cfg.config_options()[1].second, "120");
}

TEST(MosquittoModuleConfig, ReplacementConfigReplacesAndLastWins) {
    MosquittoImage cfg;
    cfg.with_config_content("listener 1883\nallow_anonymous false\n");

    const GenericImage replaced = cfg.to_generic();
    ASSERT_EQ(replaced.copy_to_sources().size(), 1u);
    EXPECT_FALSE(replaced.copy_to_sources()[0].is_file());
    EXPECT_EQ(replaced.copy_to_sources()[0].bytes(), "listener 1883\nallow_anonymous false\n");
    EXPECT_EQ(replaced.copy_to_sources()[0].target(), "/mosquitto/config/mosquitto.conf");

    // A later replacement wins over the earlier one.
    cfg.with_config("relative/broker.conf");
    const GenericImage from_file = cfg.to_generic();
    ASSERT_EQ(from_file.copy_to_sources().size(), 1u);
    EXPECT_TRUE(from_file.copy_to_sources()[0].is_file());
    EXPECT_EQ(from_file.copy_to_sources()[0].host_path().filename().string(), "broker.conf");
    EXPECT_EQ(from_file.copy_to_sources()[0].target(), "/mosquitto/config/mosquitto.conf");
}

TEST(MosquittoModuleConfig, OptionsPlusReplacementThrowAtRender) {
    EXPECT_THROW(MosquittoImage()
                     .with_config_option("persistence", "true")
                     .with_config_content("listener 1883\n")
                     .to_generic(),
                 Error);
    EXPECT_THROW(MosquittoImage()
                     .with_config("broker.conf")
                     .with_config_option("persistence", "true")
                     .to_generic(),
                 Error);
}

TEST(MosquittoModuleConfig, CustomizerRunsLastAndWins) {
    MosquittoImage cfg;
    cfg.with_customizer([](GenericImage& generic) {
           // Runs after the module's rendering, so the config copy is staged.
           ASSERT_EQ(generic.copy_to_sources().size(), 1u);
           generic.with_label("team", "iot");
       })
        .with_customizer([](GenericImage& generic) {
            generic.with_copy_to(
                CopyToContainer::content("hashed-users", "/mosquitto/config/passwd"));
        });

    const GenericImage generic = cfg.to_generic();
    ASSERT_EQ(generic.copy_to_sources().size(), 2u);
    EXPECT_EQ(generic.copy_to_sources()[1].target(), "/mosquitto/config/passwd");
    ASSERT_EQ(generic.labels().size(), 1u);
    EXPECT_EQ(generic.labels()[0].first, "team");
}

TEST(MosquittoModuleConfig, WithImageRewritesReference) {
    MosquittoImage cfg;
    cfg.with_config_option("persistence", "true")
        .with_image("mirror.example/eclipse-mosquitto:2.1-alpine");

    const GenericImage generic = cfg.to_generic();
    EXPECT_EQ(generic.image(), "mirror.example/eclipse-mosquitto");
    EXPECT_EQ(generic.tag(), "2.1-alpine");
    // The rest of the config survives the swap.
    ASSERT_EQ(generic.copy_to_sources().size(), 1u);
    EXPECT_NE(generic.copy_to_sources()[0].bytes().find("persistence true"), std::string::npos);

    cfg.with_image("eclipse-mosquitto"); // bare name defaults to "latest"
    EXPECT_EQ(cfg.to_generic().image(), "eclipse-mosquitto");
    EXPECT_EQ(cfg.to_generic().tag(), "latest");
}

TEST(MosquittoModuleConfig, RenderingIsIdempotent) {
    MosquittoImage cfg;
    cfg.with_config_option("persistence", "true");

    const GenericImage first = cfg.to_generic();
    const GenericImage second = cfg.to_generic();
    ASSERT_EQ(first.copy_to_sources().size(), 1u);
    ASSERT_EQ(second.copy_to_sources().size(), 1u); // the copy is staged once, never re-appended
    EXPECT_EQ(first.copy_to_sources()[0].bytes(), second.copy_to_sources()[0].bytes());
    ASSERT_EQ(second.waits().size(), 1u); // the log wait is baked once
}

TEST(MosquittoModuleConfig, PassThroughsLandOnTheImage) {
    MosquittoImage cfg;
    cfg.with_env("TZ", "UTC")
        .with_label("team", "iot")
        .with_network("net-a")
        .with_network_alias("broker")
        .with_reuse()
        .with_startup_timeout(std::chrono::seconds(90))
        .with_startup_attempts(2);

    const GenericImage generic = cfg.to_generic();
    ASSERT_EQ(generic.env().size(), 1u);
    EXPECT_EQ(generic.env()[0].first, "TZ");
    ASSERT_EQ(generic.labels().size(), 1u);
    EXPECT_EQ(generic.labels()[0].first, "team");
    EXPECT_EQ(generic.network().value_or(""), "net-a");
    ASSERT_EQ(generic.network_aliases().size(), 1u);
    EXPECT_EQ(generic.network_aliases()[0], "broker");
    EXPECT_TRUE(generic.reuse());
    EXPECT_EQ(generic.startup_timeout(), std::chrono::seconds(90));
    EXPECT_EQ(generic.startup_attempts(), 2);
}
